#server:
#  port: 8086
#  
#spring:
#  application:
#    name: API-GATEWAY
#    
#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri: http://localhost:8082
#        predicates:
#        - Path=/api/user/**
#        filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userservicefallback  
#          
#          
#      - id: LOAN-SERVICE
#        uri: http://localhost:8081
#        predicates:
#         - Path=/api/Loan/**  
#        filters:
#           - name: 
#             args:
#               name: LOAN-SERVICE
#               fallbackuri: forward/departmentservicefb
#               
#hystrix:
#  command: 
#  fallbackcmd:
#   execution:
#    isolation:
#     thread:
#   timeoutInMiliseconds: 4000                  
#
#   
#
#   
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream    
#   
#   
#       
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost      
#              
#================================================

server:
  port: 8086

spring:
  application:
    name: API-Gateway
    
    
  cloud:
      gateway:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/user/**
            filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userservicefallback   
              
              
              
          - id: LOAN-SERVICE
            uri: lb://LOAN-SERVICE
            predicates:
              - Path=/api/Loan/**
            filters:
            - name: CircuitBreaker
              args:
                name: LOAN-SERVICE
                fallbackuri: forward/departmentservicefb  
                
                
hystrix:
  command: 
  fallbackcmd:
   execution:
    isolation:
     thread:
   timeoutInMiliseconds: 4000                  
   
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream               
              

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


         